version: '3.9'
services:
  node:
    working_dir: /app
    build: "./"
    restart: always
    command: ["npm","start"]
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: "production"
      PORT: 8080
      DB_URL_BASE: mongodb://mongo:27017/i-bms
      AUTH0_AUDIENCE: https://express.sample
      AUTH0_DOMAIN: https://dev-n8d0f7yf.au.auth0.com/

  mongo:
    image: mongo:4.0-xenial
    restart: always
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 4dO9Y50u62d
    volumes:
      - ibms:/data/db

volumes:
  ibms:
