version: '3'
services:
  node:
    working_dir: /app
    build: "./"
    restart: always
    command: ["npm","start"]
    
    environment:
      NODE_ENV: "production"
      PORT: 8080
      DB_URL_BASE: mongodb+srv://e_mob:KzweuGpSi2cQj1Yo@e-mobility.0vu1kp0.mongodb.net/i_bms
      AUTH0_AUDIENCE: https://express.sample
      AUTH0_DOMAIN: https://dev-n8d0f7yf.au.auth0.com/
    
    ports:
      - "8080:8080"





networks:
  default:
    name: mongodb_network
