version: '3.9'
services:
  app:
    working_dir: /app
    build: "./"
    restart: always
    command: ["npm","start"]
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: "production"
      PORT: 8080
      DB_URL_BASE: mongodb+srv://m001-student:m001-mongodb-basics@sandbox.kc4te.mongodb.net
      AUTH0_AUDIENCE: https://express.sample
      AUTH0_DOMAIN: https://dev-n8d0f7yf.au.auth0.com/


    networks:
      - all


networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
